name: "Инфо о PR"

on:
  pull_request:
  workflow_dispatch:

jobs:
  Rabota:
    name: "Работаем"
    runs-on: ubuntu-latest

    steps:
    - name: "Качаем репозиторий с PR"
      uses: actions/checkout@v3
      with: { fetch-depth: 0 }

    - name: "Изучаем"
      run: |
        # Сохраняем заголовки и описания коммитов в строку
        # Переменная {{ github.event.sender.commits }} содержит число коммитов
        # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads
        COMMITS=`git log --format=%B -n${{ github.event.sender.commits }}`
        
        echo "Коммиты: $COMMITS"
        

        # Ищем в строке [cache clear]
        if [[ "$COMMITS" == *"[clear cache]"* ]]; then
          echo "Нужно очищать!"
        fi
