name: "Инфо о PR"

on:
  pull_request:

jobs:
  Rabota:
    name: "Работаем"
    runs-on: ubuntu-latest

    steps:
    - name: "Качаем репозиторий с PR"
      uses: actions/checkout@v3
      with: { fetch-depth: 0 }

    - name: "Изучаем"
      run: |
        # Сохраняем заголовки и описания коммитов в строку
        # Переменная {{ github.event.pull_request.commits }} содержит число коммитов в PR
        COMMITS=`git log --format=%B -n${{ github.event.pull_request.commits }}`
        
        echo "Коммиты: $COMMITS"
        

        # Ищем в строке [cache clear]
        if [[ "$COMMITS" == *"[cache cleor]"* ]]; then
          echo "Нужно очищать!"
        fi

