name: "Инфо о PR"

on:
  pull_request:

jobs:
  Rabota:
    name: "Работаем"
    runs-on: ubuntu-latest

    steps:
    - name: "Качаем репозиторий с PR"
      uses: actions/checkout@v3
      with: { fetch-depth: 0 }

    - name: "Изучаем"
      run: |
        # https://docs.github.com/en/graphql/reference/objects#pullrequest
        echo "${{ github.event.pull_request.commits }}"
