name: "Инфо о PR"

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  Rabota:
    name: "Работаем"
    runs-on: ubuntu-latest

    steps:
    - name: "Качаем репозиторий с PR"
      uses: actions/checkout@v3
      with: { fetch-depth: 0 }

      # https://docs.github.com/en/actions/learn-github-actions/expressions
    - name: "Изучаем"
      if: |
        contains(join(github.event.commits.*.message, ' '), '[clear cache]')

      run: |
        echo "!!!!Startanulo"
        
        
        
        
        
        
        

